---
title: html5幻灯片简介 
subtitle: 利用slidify 和 knitr创建基于html5 的slides 
author: 周扬 
github: {user: ramnathv, repo: rCharts, branch: "gh-pages"}
framework: shower
mode: selfcontained
ext_widgets: {rCharts: ["libraries/morris","libraries/nvd3", "libraries/polycharts", "libraries/highcharts","libraries/xcharts", "libraries/leaflet", "libraries/rickshaw"]}
hitheme: solarized_light
logo: libraries/frameworks/minimal/images/rCharts.png
---

## html5幻灯片演示

1. slidify 是R语言下利用markdown标记语言生成html5 slides 的包。
2. 主要的特点包括：可交互、可重复和避免直接使用html标记语言。
3. 使用三个减号“-” 作为不同页面间的切换。
4. 可灵活调用第三方的js库和模板。

--- .class #id 

## Slide 2
###当然，最酷的是，我们可以将动态可交互的图形嵌入幻灯片中。
###就用recharts 来试一试吧？

---
## Slide 3

```{r echo = F, message = F, results='asis', tidy=FALSE}
library(recharts)
op <- options(recharts.plot.tag='chart')
recharts.init()
# rForce Chart
# R script here
networkMatrix <- matrix(c(
	c(0, 1, 2, 1, 2, 3, 6, 6, 1, 1, 1 ),
	c(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ),
	c(2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0 ),
	c(1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0 ),
	c(2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ),
	c(3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ),
	c(6, 0, 1, 1, 1, 1, 0, 6, 0, 1, 0 ),
	c(6, 0, 0, 1, 0, 0, 6, 0, 0, 0, 0 ),
	c(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ),
	c(1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ),
	c(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 )
	), ncol=11
)


propertyDf <- data.frame(
	category = c("a", "b", "b", "b", "b", "c", 
				"c", "c", "c", "c", "c"),
	name = c("Steven Jobs", "Lisa Jobs", "Paul Jobs", " Kalala Jobs",
			"Lauren Powell", "Steve woz Ike", "Obama", "Bill Gates", 
			"Jonathan", "Tim Cook", "Wayne"),
	value = c(10, 2, 3, 3, 7, 5, 8, 9, 4, 4, 0)
 )

rownames(propertyDf) = propertyDf$name

recharts.eForce <- eForce(networkMatrix=networkMatrix, propertyDf=propertyDf, size=c(800,400))

plot(recharts.eForce)

```

---
## Slide 4

```{r echo = F, message = F, results='asis', tidy=FALSE}
op <- options(recharts.plot.tag='chart')

recharts.eLine <- eLine(WorldPhones, size=c(800,400))
plot(recharts.eLine)
```
---

## Slide 5

```{r echo = F, message = F, results='asis', tidy=FALSE}
op <- options(recharts.plot.tag='chart')

x = sample(4)
names(x) = LETTERS[1:4]
recharts.ePie <- ePie(x, size=c(800,400))
plot(recharts.ePie)

```
---
```{r echo = F, message = F, results='asis', tidy=FALSE}
op <- options(recharts.plot.tag='chart')

require(plyr)
dat = ddply(iris, .(Species), colwise(mean))
rownames(dat) = dat[,1]
dat = dat[, -1]

recharts.eBar <- eBar(dat, size=c(800,400))
plot(recharts.eBar)
```

---

```{r echo = F, message = F, results='asis', tidy=FALSE}
op <- options(recharts.plot.tag='chart')

# Map
load(url('http://yzhou.org/recharts/ChinaGDP.RData'))
recharts.eMap <- eMap(ChinaGDP, size=c(800,400))
plot(recharts.eMap)

```


