# 高级绘图函数 {#nbFunction}

```{r echo = FALSE}
library(recharts)
```

## 堆砌区域图
```{r}
require(plyr)
eArea(WorldPhones, theme=1)
#mode 2 input.
df2 <- data.frame(
  saleNum=c(10,20,30,40,50,60,70,15,25,35,45,55,65,75,25,35,45,55,65,75,85),
  seller=c(rep("Yellow",7), rep("Red",7), rep("White",7)),
	 weekDay = c(rep(c("Mon","Tue","Wed","Thu","Fri","Sat","Sun"),3)),
  stringsAsFactors =FALSE
)
eArea(df2, xvar=~weekDay, yvar= ~saleNum, series=~seller)

dat <- cut(rnorm(1000), -4:4)
eArea(dat)
```

## K线图

```{r}
mat = rbind(c(2286.33,2299.99,2281.9,2309.39),
            c(2297.11,2305.11,2290.12,2305.3),
            c(2303.75,2302.4,2292.43,2314.18),
            c(2293.81,2275.67,2274.1,2304.95),
            c(2281.45,2288.53,2270.25,2292.59),
            c(2286.66,2293.08,2283.94,2301.7),
            c(2293.4,2321.32,2281.47,2322.1),
            c(2323.54,2324.02,2321.17,2334.33),
            c(2316.25,2317.75,2310.49,2325.72),
            c(2320.74,2300.59,2299.37,2325.53),
            c(2300.21,2299.25,2294.11,2313.43),
            c(2297.1,2272.42,2264.76,2297.1),
            c(2270.71,2270.93,2260.87,2276.86),
            c(2264.43,2242.11,2240.07,2266.69),
            c(2242.26,2210.9,2205.07,2250.63),
            c(2190.1,2148.35,2126.22,2190.1)
)
rownames(mat) = Sys.Date()-(16:1)
eCandle(mat)
eCandle(mat, theme = 1)
```

## 漏斗图

```{r}
x = c("Exposure" = 100, "Click" = 80, "Visit" = 60, "Query"=40, "Buy"=20)
eFunnel(x) +eTitle(title = "Funnel Plot")
funnelDf <- data.frame(namevar = c("Exposure", "Click", "Visit", "Query", "Buy"),
   datavar = c(100, 80, 60, 40, 20), stringsAsFactors=FALSE)
eFunnel(funnelDf, ~namevar, ~datavar, theme =1)
```

## 平行坐标
```{r}
require(plyr)

axisList = list(
	list(index=7, type="category", data = c("low", "middle", "high")),
	list(index=6, inverse=TRUE, max=50, nameLocation="start")
)
eParallel(head(parallelDf, 20), series=~groupName, axisList = axisList)
```

## 雷达图
```{r}
require(plyr)
dat = ddply(iris, .(Species), colwise(mean))
rownames(dat) = dat[,1]
dat = dat[, -1]
dat
eRadar(dat)
df2 <- data.frame(
 saleNum=c(10,20,30,40,50,60,70,15,25,35,45,55,65,75,25,35,45,55,65,75,85),
	seller=c(rep("Yellow",7), rep("Red",7), rep("White",7)),
weekDay = c(rep(c("Mon","Tue","Wed","Thu","Fri","Sat","Sun"),3))
)
dat <- df2
xvar=~weekDay; yvar= ~saleNum; series=~seller
eRadar(df2, ~weekDay, ~saleNum, ~seller)
dat = data.frame(IE8 = (40 - 1:28) * 10,
                 IE9 = (38 - 1:28) * 4 + 60,
                 Safari = 1:28 * 5 + 10,
                 Firefox = 1:28 * 9,
                 Chrome = 1:28 * 1:28 /2)
row.names(dat) = 2001:2028
chart = eRadar(dat, ymax = rep(400,5))
chart$x$visualMap=list(color=c('red','yellow'))
chart
```

## 水球图
```{r}
eLiquid(0.6)
eLiquid(0.6,wave = 6)
```

## 桑基图
```{r}
dat = data.frame(source=c("Agricultural 'waste'","Bio-conversion",
                          "Bio-conversion","Bio-conversion","Bio-conversion",
                          "Biofuel imports","Biomass imports","Coal imports",
                          "Coal reserves","Coal","District heating","District heating",
                          "District heating","Electricity grid","Electricity grid"),
                 target=c("Bio-conversion","Liquid","Losses","Solid","Gas","Liquid",
                          "Solid","Coal","Coal","Solid","Industry","Heating and cooling - commercial",
                          "Heating and cooling - homes","Over generation / exports","Heating and cooling - homes"),
                 value=c(124.729,0.597,26.862,280.322,81.144,35,35,11.606,63.965,75.571,
                         10.639,22.505,46.184,104.453,113.726))
eSankey(dat)
```


## 词云
```{r}
eWordcloud(wordFreqDf_chs, namevar = ~Word, datavar = ~Freq)
```

## 地图
```{r}
mapData <- head(mapTestData_chs, 5)
eMap(mapData, namevar=~stdName, datavar = ~val1 + val2)
provinceMapData <- mapTestData_chs[6:15,]
eMap(provinceMapData, namevar=~stdName, datavar = ~val1+val2, region=unique(provinceMapData$motherName)[1])
```
